//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stsmeepupBOT.BDConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class connectChatAdmin
    {
        public int id_connect { get; set; }
        public int id_chat { get; set; }
        public Nullable<int> id_admin { get; set; }
    
        public virtual admins admins { get; set; }
        public virtual chats chats { get; set; }
    }
}
