//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stsmeepupBOT.BDConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meetings()
        {
            this.finishedMeetings = new HashSet<finishedMeetings>();
        }
    
        public int id_meeting { get; set; }
        public int id_chat { get; set; }
        public string titleMeeting { get; set; }
        public string descriptionMeeting { get; set; }
        public System.DateTime dateCreateMeeting { get; set; }
        public int notificationMeeting { get; set; }
        public System.DateTime dateEventMeeting { get; set; }
        public int statusMeeting { get; set; }
    
        public virtual typeStatusMeeting typeStatusMeeting { get; set; }
        public virtual chats chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<finishedMeetings> finishedMeetings { get; set; }
    }
}
